baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.markkulab.net/" # the base hostname & protocol for your site, e.g. http://example.com
web_site_domain: "https://blog.markkulab.net" 


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap  
  - jekyll-seo-tag
paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# 全域 seo   
title: "Eden's Blog" # 網站的名稱
locale: "zh-TW" # 自己的地區
description: "EDEN Y. Makeup studio | 歐美造型 |歐美妝 |新娘造型 |外拍婚紗 |不凋花造型 |不凋花花圈 |永生花造型 |永生花花圈 |新娘秘書推薦 |新秘 |新秘教學 |婚紗造型"
url: "https://www.edenyang.com/" # 自己部落格的網址
  
